language: generic

os: osx
osx_image: xcode7.3
env: 
          - TARGET_SYSTEM=OSX
            PYTHON=/usr/local/bin/python
            JPEG=/usr/local/opt/mozjpeg
            STEP=2
before_script:
  - ./dep-install.sh $STEP
  - cd $HOME
  - tar czf $HOME/homebrew-cache-pf-step${STEP}.tar.gz homebrew
  - wget -c https://github.com/aferrero2707/uploadtool/raw/master/upload_rotate.sh
  - bash  ./upload_rotate.sh "continuous" $HOME/homebrew-cache-pf-step${STEP}.tar.gz


branches:
  except:
    - # Do not build tags that we create when we upload to GitHub Releases
    - /^(?i:continuous)$/
    - /^(?i:unstable)$/
